"""Compatibility alias for legacy llm_interface import path.

All symbols are re-exported from companion_ai.llm for backward compatibility.
"""

import sys as _sys

from companion_ai.llm import (
    sanitize_output,
    get_groq_client,
    groq_client,
    groq_tool_client,
    groq_memory_client,
    generate_model_response_with_tools,
    generate_model_response,
    generate_model_response_streaming,
    generate_groq_response,
    get_embedding,
    get_embeddings_batch,
    generate_local_response,
    OLLAMA_URL,
    OLLAMA_TEXT_MODEL,
    OLLAMA_VISION_MODEL,
    OLLAMA_EMBED_MODEL,
    OLLAMA_CODE_MODEL,
    generate_response,
    generate_response_streaming,
    extract_profile_facts,
    generate_summary,
    generate_insight,
    reset_last_request_tokens,
    get_last_token_usage,
    log_tokens_step,
    log_tokens,
    get_token_stats,
    reset_token_stats,
)

__all__ = [
    "sanitize_output",
    "get_groq_client",
    "groq_client",
    "groq_tool_client",
    "groq_memory_client",
    "generate_model_response_with_tools",
    "generate_model_response",
    "generate_model_response_streaming",
    "generate_groq_response",
    "get_embedding",
    "get_embeddings_batch",
    "generate_local_response",
    "OLLAMA_URL",
    "OLLAMA_TEXT_MODEL",
    "OLLAMA_VISION_MODEL",
    "OLLAMA_EMBED_MODEL",
    "OLLAMA_CODE_MODEL",
    "generate_response",
    "generate_response_streaming",
    "extract_profile_facts",
    "generate_summary",
    "generate_insight",
    "reset_last_request_tokens",
    "get_last_token_usage",
    "log_tokens_step",
    "log_tokens",
    "get_token_stats",
    "reset_token_stats",
]